CREATE TABLE IF NOT EXISTS budgets (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS budget_categories (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  budget_id INTEGER NOT NULL,
  amount DOUBLE(13, 2) NOT NULL,
  CONSTRAINT FK_CategoryBudget FOREIGN KEY (budget_id) REFERENCES budgets(id)
);

INSERT INTO budgets (name) VALUES ("Everyday");
