CREATE TABLE categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date INTEGER NOT NULL,
  category INTEGER,
  title TEXT NOT NULL,
  cost REAL NOT NULL,
  CONSTRAINT FK_ExpenseCategory FOREIGN KEY (category) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE expense_tags (
  expense_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  CONSTRAINT FK_ExpenseId FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE,
  CONSTRAINT FK_TagId FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
